### ISSUE TITLE
Error in accessing template backend.

### ISSUE THREAD

**Issue by templatedop** [leaderit/graphql-postgres-template#1]
Firstly...

Thank you for this wonderful template.

Kindly help me to resolve it.

When I tried to open minio through browser it asks for access key and secret key.They were never configured. Kindly help to configure them.

Also minio_root_user, minio_root_password,storage_user, storage_password were not available in env example file. I just added some values. Is it OK. I would like to implement  and understand it. KINDLY HELP.

When I ./run-tests  I get following error:

```
> server@1.0.0 test /server
> tap -t36000 test/**/*.test.js

sh: 1: tap: not found
npm ERR! Test failed.  See above for more details.
```

I get following error in debug mode:

```
graphql-postgres-template-backend |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
graphql-postgres-template-backend |     at require (internal/modules/cjs/helpers.js:88:18)
graphql-postgres-template-backend |     at Object.<anonymous> (/server/server.js:4:17)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
graphql-postgres-template-backend |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
graphql-postgres-template-backend |     at Module.load (internal/modules/cjs/loader.js:928:32)
graphql-postgres-template-backend |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
graphql-postgres-template-backend |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30) {
graphql-postgres-template-backend |   code: 'MODULE_NOT_FOUND',
graphql-postgres-template-backend |   requireStack: [ '/server/server.js' ]
graphql-postgres-template-backend | }
graphql-postgres-template-backend | 2021-01-19T10:42:17: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
graphql-postgres-template-backend | 2021-01-19T10:42:17: PM2 log: Script /server/server.js had too many unstable restarts (16). Stopped. "errored"
graphql-postgres-template-backend | 2021-01-19T10:42:18: PM2 log: 0 application online, retry = 3
graphql-postgres-template-backend | 2021-01-19T10:42:20: PM2 log: 0 application online, retry = 2
graphql-postgres-template-backend | 2021-01-19T10:42:22: PM2 log: 0 application online, retry = 1
graphql-postgres-template-backend | 2021-01-19T10:42:24: PM2 log: 0 application online, retry = 0
graphql-postgres-template-backend | 2021-01-19T10:42:24: PM2 log: [Watch] Stop watching server
graphql-postgres-template-backend | 2021-01-19T10:42:24: PM2 log: Stopping app:server id:0
graphql-postgres-template-backend | 2021-01-19T10:42:24: PM2 error: app=server id=0 does not have a pid
graphql-postgres-template-backend | 2021-01-19T10:42:24: PM2 log: PM2 successfully stopped
graphql-postgres-template-backend exited with code 0
graphql-postgres-template-backend | 2021-01-19T10:42:25: PM2 log: Launching in no daemon mode
graphql-postgres-template-backend | 2021-01-19T10:42:25: PM2 log: [Watch] Start watching server
graphql-postgres-template-backend | 2021-01-19T10:42:25: PM2 log: App [server:0] starting in -fork mode-
graphql-postgres-template-backend | 2021-01-19T10:42:25: PM2 log: App [server:0] online
graphql-postgres-template-backend | Error: Cannot find module 'fastify'
graphql-postgres-template-backend | Require stack:
graphql-postgres-template-backend | - /server/server.js
graphql-postgres-template-backend |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
graphql-postgres-template-backend |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
graphql-postgres-template-backend |     at require (internal/modules/cjs/helpers.js:88:18)
graphql-postgres-template-backend |     at Object.<anonymous> (/server/server.js:4:17)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
graphql-postgres-template-backend |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
graphql-postgres-template-backend |     at Module.load (internal/modules/cjs/loader.js:928:32)
graphql-postgres-template-backend |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
graphql-postgres-template-backend |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30) {
graphql-postgres-template-backend |   code: 'MODULE_NOT_FOUND',
graphql-postgres-template-backend |   requireStack: [ '/server/server.js' ]
graphql-postgres-template-backend | }
graphql-postgres-template-backend | 2021-01-19T10:42:25: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
graphql-postgres-template-backend | 2021-01-19T10:42:25: PM2 log: App [server:0] starting in -fork mode-
graphql-postgres-template-backend | 2021-01-19T10:42:25: PM2 log: App [server:0] online
graphql-postgres-template-backend | Error: Cannot find module 'fastify'
graphql-postgres-template-backend | Require stack:
graphql-postgres-template-backend | - /server/server.js
graphql-postgres-template-backend |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
graphql-postgres-template-backend |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
graphql-postgres-template-backend |     at require (internal/modules/cjs/helpers.js:88:18)
graphql-postgres-template-backend |     at Object.<anonymous> (/server/server.js:4:17)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
graphql-postgres-template-backend |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
graphql-postgres-template-backend |     at Module.load (internal/modules/cjs/loader.js:928:32)
graphql-postgres-template-backend |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
graphql-postgres-template-backend |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30) {
graphql-postgres-template-backend |   code: 'MODULE_NOT_FOUND',
graphql-postgres-template-backend |   requireStack: [ '/server/server.js' ]
graphql-postgres-template-backend | }
graphql-postgres-template-backend | 2021-01-19T10:42:26: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
graphql-postgres-template-backend | 2021-01-19T10:42:26: PM2 log: App [server:0] starting in -fork mode-
graphql-postgres-template-backend | 2021-01-19T10:42:26: PM2 log: App [server:0] online
graphql-postgres-template-backend | Error: Cannot find module 'fastify'
graphql-postgres-template-backend | Require stack:
graphql-postgres-template-backend | - /server/server.js
graphql-postgres-template-backend |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
graphql-postgres-template-backend |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
graphql-postgres-template-backend |     at require (internal/modules/cjs/helpers.js:88:18)
graphql-postgres-template-backend |     at Object.<anonymous> (/server/server.js:4:17)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
graphql-postgres-template-backend |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
graphql-postgres-template-backend |     at Module.load (internal/modules/cjs/loader.js:928:32)
graphql-postgres-template-backend |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
graphql-postgres-template-backend |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30) {
graphql-postgres-template-backend |   code: 'MODULE_NOT_FOUND',
graphql-postgres-template-backend |   requireStack: [ '/server/server.js' ]
graphql-postgres-template-backend | }
graphql-postgres-template-backend | 2021-01-19T10:42:26: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
graphql-postgres-template-backend | 2021-01-19T10:42:26: PM2 log: App [server:0] starting in -fork mode-
graphql-postgres-template-backend | 2021-01-19T10:42:26: PM2 log: App [server:0] online
graphql-postgres-template-backend | Error: Cannot find module 'fastify'
graphql-postgres-template-backend | Require stack:
graphql-postgres-template-backend | - /server/server.js
graphql-postgres-template-backend |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
graphql-postgres-template-backend |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
graphql-postgres-template-backend |     at require (internal/modules/cjs/helpers.js:88:18)
graphql-postgres-template-backend |     at Object.<anonymous> (/server/server.js:4:17)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
graphql-postgres-template-backend |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
graphql-postgres-template-backend |     at Module.load (internal/modules/cjs/loader.js:928:32)
graphql-postgres-template-backend |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
graphql-postgres-template-backend |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30) {
graphql-postgres-template-backend |   code: 'MODULE_NOT_FOUND',
graphql-postgres-template-backend |   requireStack: [ '/server/server.js' ]
graphql-postgres-template-backend | }
graphql-postgres-template-backend | 2021-01-19T10:42:26: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
graphql-postgres-template-backend | 2021-01-19T10:42:26: PM2 log: App [server:0] starting in -fork mode-
graphql-postgres-template-backend | 2021-01-19T10:42:26: PM2 log: App [server:0] online
graphql-postgres-template-backend | Error: Cannot find module 'fastify'
graphql-postgres-template-backend | Require stack:
graphql-postgres-template-backend | - /server/server.js
graphql-postgres-template-backend |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
graphql-postgres-template-backend |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
graphql-postgres-template-backend |     at require (internal/modules/cjs/helpers.js:88:18)
graphql-postgres-template-backend |     at Object.<anonymous> (/server/server.js:4:17)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
graphql-postgres-template-backend |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
graphql-postgres-template-backend |     at Module.load (internal/modules/cjs/loader.js:928:32)
graphql-postgres-template-backend |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
graphql-postgres-template-backend |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
graphql-postgres-template-backend |     at Module._compile (internal/modules/cjs/loader.js:1063:30) {
graphql-postgres-template-backend |   code: 'MODULE_NOT_FOUND',
graphql-postgres-template-backend |   requireStack: [ '/server/server.js' ]
graphql-postgres-template-backend | }

```

**Comment by leaderit** [comment]
For now I wrote readme on russian. I will translate it to English soon.

I just added access enviroment for min.io into env-example, use the update

steps for install the template for your new project are:

1. mkdir my-project
2. cd my-project 
3. git clone https://github.com/leaderit/graphql-postgres-template.git .
4. cp env-example .env
5. cp server/env-example server/.env
5. EDIT .env  and set NAME variable to "my-project"
6. set other variables in apropriate values, espetialy passwords
7. cd server
8. npm install
9. cd ..
10. docker-compose up -d

it will takes time ... and will finished by:

Creating my-project-storage  ... done
Creating my-project-postgres ... done
Creating my-project-redis    ... done
Creating my-project-backend  ... done
Creating my-project-graphql  ... done
Creating my-project-pgadmin  ... done
Creating my-project-proxy    ... done

check all started images by 'docker ps' command.
I just did all that steps and result is:

129273209ebf   my-project_proxy                                 "/docker-entrypoint.…"   39 seconds ago   Up 37 seconds                0.0.0.0:8088->80/tcp                             my-project-proxy
140813c9abf2   hasura/graphql-engine:v1.3.3.cli-migrations-v2   "docker-entrypoint.s…"   40 seconds ago   Up 6 seconds                 0.0.0.0:8081->8080/tcp                           my-project-graphql
1aaca6d3554f   dpage/pgadmin4                                   "/entrypoint.sh"         40 seconds ago   Up 38 seconds                443/tcp, 0.0.0.0:5051->80/tcp                    my-project-pgadmin
71c83bfc0382   my-project_backend                               "docker-entrypoint.s…"   40 seconds ago   Up 39 seconds                80/tcp                                           my-project-backend
994eec723588   redis:alpine                                     "docker-entrypoint.s…"   40 seconds ago   Up 39 seconds                0.0.0.0:6379->6379/tcp                           my-project-redis
3d3af6556d8e   my-project_postgres                              "docker-entrypoint.s…"   40 seconds ago   Up 39 seconds                0.0.0.0:5432->5432/tcp                           my-project-postgres
8940d5bf7f54   minio/minio                                      "/usr/bin/docker-ent…"   40 seconds ago   Up 39 seconds (healthy)      0.0.0.0:9000->9000/tcp                           my-project-storage

IMPORTENT!!! INIT database and metadata (one time action)
11. ./hasura-cli migrate apply 
INFO migrations applied 

12. ./hasura-cli metadata apply
INFO Metadata applied 

13. ./hasura-cli seeds apply
INFO Seeds planted

run tests by ./run-tests
result is:


> server@1.0.0 test /server
> tap -t36000 test/**/*.test.js

test/plugins/backend.test.js .......................... 2/2 2s
test/plugins/hasura.test.js ........................... 2/2 2s
test/plugins/redisEvents.test.js ...................... 2/2 2s
test/plugins/support.test.js .......................... 2/2 2s
test/services/auth.test.js .......................... 15/15
test/services/hasura-auth.test.js ..................... 2/2 2s
test/services/register.test.js ...................... 70/70
total ............................................... 95/95

  95 passing (14s)

  ok

tests not for all functions for now, sorry.

open http://localhost:8088/hasura/
in browser 

enter password from HASURA_ADMIN_SECRET variable

and play in graphql console

Later i will write confugure.sh script for quick setup. The project contain some test code and files. it will remove befor creating release branch 

project is in active development for using in business projects - i will up it to good quality level
Thank you for interest and feedback, it helps to do the project better 

Wbr, Valerii

**Comment by leaderit** [comment]
use latest version of the template - i exported new metadata and init migration

**Comment by templatedop** [comment]
That's great brother.
I  translated  using google translator.
I need this to be implemented in my project.
And the template provided by you is great.
Kindly help me.

I will do as guided by you and update you shortly.

Thanks for all guidance provided up to now.

**Comment by templatedop** [comment]
> use latest version of the template - i exported new metadata and init migration

Hey! Thank you.

No errors.
Everything got installed as expected.

Now. I need to work on Actions then.

Kindly help me how to implement Register action.

I just tried to query like this:
query MyQuery {
  register(login: "ram1", password: "ram1", password2: "ram1") {
    user_id
  }
}

I sure it is wrong.
Becoz 500 error is thrown.

Please guide me. Small hint will help.

Could see Codegen tab.

But please guide.....

I would like to implement in one live project to get hands on.

**Comment by leaderit** [comment]
Now quick start is:

    mkdir my-project
    cd my-project
    curl https://raw.githubusercontent.com/leaderit/graphql-postgres-template/main/configure.sh | bash -s --

**Comment by leaderit** [comment]
the project made for web AND mobile backend. So, you must register Client application and use it for register, login etc operations.

for default data request may be something like this:

query Register(
    $password: String!, 
    $password2: String!, 
    $login: String!, 
    $scope: String = "", 
    $client_secret: String = "", 
    $client_id: String = ""
    $org_id: uuid
) {
  register ( 
        password: $password,
        password2: $password2,  
        login: $login, 
        client_id: $client_id, 
        client_secret: $client_secret, 
        scope: $scope
        org_id: $org_id
    ){
    access_token
    refresh_token
    success
    error
    user_id
    expires_in
    token_type
  }
}

Variables are:
{
    "client_id":"ios-v1",
    "client_secret":"supersecret",
    "scope":"",
    "login":"login9",
    "password":"password",
    "password2":"password",
    "org_id": null
}

**Comment by leaderit** [comment]
Look into server/gql/auth.gql.js
and tests/*

register/unregister testing is works. I did tests on 100K restrations. All works wine - no one error

**Comment by leaderit** [comment]
and i just added my postman collection requests into doc directory.
Just import it and play on all

**Comment by leaderit** [comment]
You can open new issue on new problem
