### ISSUE TITLE
Guidance on Table Permissions 

### ISSUE THREAD

**Issue by templatedop** [leaderit/graphql-postgres-template#2]
Hi!

Request to please guide on table permissions.

 I am adding a column to map X-Hasura-User-Id for row-level permissions.

This is a bit overhead. 

I may have to add userid column for every table for mapping.

Is there a better way to deal this.

Kindly guide.

For example for a table named Transactions I added userid column just for mapping permissions with x-hasura-user-id

CREATE TABLE public.transactions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    "Transaction_name" text COLLATE pg_catalog."default" NOT NULL,
    amount integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    **userid** text COLLATE pg_catalog."default",
    CONSTRAINT transactions_pkey PRIMARY KEY (id)
)

![image](https://user-images.githubusercontent.com/23015340/105571686-1aadf980-5d78-11eb-9a15-57a0ed82bea0.png)

**Comment by leaderit** [comment]
see example on an exists tables. user, for example.

Until login rights group = anonymous
after login - as selecter in group_id field of the user.

if you want restrict access to the record based on user, set something like this (look at the files table).

{"_or":[{"owner_id":{"_eq":"X-Hasura-User-Id"}},{"_and":[{"org_id":{"_eq":"X-Hasura-Org-Id"}},{"public":{"_eq":true}}]}]}

and do not forget update a user_id field when you add or update the record.

set owner_id to X-Hasura-User-d
sen org_id to X-Hasura-Org-Id

and then use values for check access rights

**Comment by leaderit** [comment]
look at

https://hasura.io/docs/1.0/graphql/core/auth/authorization/index.html

**Comment by templatedop** [comment]
Thanks brother.
