### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by templatedop** [leaderit/graphql-postgres-template#3]
Hey!

I was unable to  upload files based on postman collection shared.

Please guide.

Added token in Authorisation header and then tried to upload file through form-data in postman client.

The response was 403 Forbidden error.

Please guide. 

I am sure I am missing something.

Screenshot is attached for info.

<img width="965" alt="Screenshot 2021-01-23 at 3 08 50 PM" src="https://user-images.githubusercontent.com/23015340/105574954-f9580800-5d8d-11eb-995b-1740cf3a7448.png">

**Comment by leaderit** [comment]
1. create record for the file (in console, for example, or under admin because rights not set up now)
2. use the record id for the file_id field - you upload registered file only

File storage not use min.io now - i working on it

**Comment by leaderit** [comment]
you can use for test
1. login
2. create file in console
3. upload
4. get file - for check url

the function works fine, but not documented yet ))

**Comment by leaderit** [comment]
Please check new set of Postman requests examples - it works fine for
all steps:

- login
- get url for new file
- upload it via PUT request in a binary mode
- get url of the uploaded file
- get the file via the url

In additional look into test/service directory for tests source code. You'll find

- delete file
- move file
- copy file
- create storage
- delete storage

and more via Axios requests
run ./run-tests
for check functionality works fine.

all works fine on develop and clean system.

**Comment by leaderit** [comment]
I did tests for check upload/get/delete/copy/move files in a Min.IO storage - all works fine now

**Comment by templatedop** [comment]
Hey!

Thanks for update. Hope doing well.



I tried for 
```
mutation StorageNewFile($path: String! = "", $name: String = "", $storage: String! = "") {
  storage_newfile(path: $path, storage: $storage, name: $name) {
    url
  }
}

```

And variable as 
```
{
    "path":"",
    "storage":"users",
    "name":"newfile.mp4"
}

```

The result is:

```
{
    "errors": [
        {
            "extensions": {
                "internal": {
                    "error": "expecting 2xx or 4xx status code, but found 500",
                    "response": {
                        "status": 500,
                        "body": {
                            "error": "Internal Server Error",
                            "code": "NoSuchBucket",
                            "message": "The specified bucket does not exist",
                            "statusCode": 500
                        },
                        "headers": [
                            {
                                "value": "Origin",
                                "name": "vary"
                            },
                            {
                                "value": "false",
                                "name": "access-control-allow-origin"
                            },
                            {
                                "value": "120",
                                "name": "content-length"
                            },
                            {
                                "value": "application/json; charset=utf-8",
                                "name": "content-type"
                            },
                            {
                                "value": "Tue, 02 Mar 2021 10:25:44 GMT",
                                "name": "Date"
                            },
                            {
                                "value": "keep-alive",
                                "name": "Connection"
                            },
                            {
                                "value": "timeout=5",
                                "name": "Keep-Alive"
                            }
                        ]
                    },
                    "request": {
                        "body": {
                            "session_variables": {
                                "x-hasura-role": "user",
                                "x-hasura-token": "ad2a84c3bf4fa3b5d60a71d568b9ce580f8bdece5e8a262d2019fd5a213360da",
                                "x-hasura-user-id": "7f9d490c-7b3e-11eb-a466-a7475fa27e28",
                                "x-hasura-org-id": ""
                            },
                            "input": {
                                "path": "",
                                "storage": "users",
                                "name": "newfile.mp4"
                            },
                            "action": {
                                "name": "storage_newfile"
                            }
                        },
                        "url": "http://backend:3000/api/s3/io",
                        "headers": [
                            {
                                "value": "PostmanRuntime/7.26.8",
                                "name": "X-Forwarded-User-Agent"
                            },
                            {
                                "value": "localhost:8081",
                                "name": "X-Forwarded-Host"
                            },
                            {
                                "value": "Bearer ad2a84c3bf4fa3b5d60a71d568b9ce580f8bdece5e8a262d2019fd5a213360da",
                                "name": "Authorization"
                            },
                            {
                                "value": "216379ad-1081-4f7f-b1a1-fda6a7d09b96",
                                "name": "Postman-Token"
                            }
                        ]
                    }
                },
                "path": "$",
                "code": "unexpected"
            },
            "message": "internal error"
        }
    ]
}

```





I even tried  

```
query StorageFileUrl($path: String! = "", $name: String! = "", $storage: String! = "") {
  storage_fileurl(path: $path, storage: $storage, name: $name) {
    url
  }
}
```
with variables as

```
{
    "path":"",
    "storage":"users",
    "name":"newfile.mp4"
}
```

**I might be missing something please guide.**


This was tried only login and also providing token while executing request.

**Comment by templatedop** [comment]
An update:

 Created storage name 'admin' manually after login to http://localhost:9000/minio/ in browser.



Then I was able to upload file to admin storage through postman client

One file was uploaded through browser using storage user.

But was able to access the file through different user.

Please guide.

**Comment by leaderit** [comment]
> An update:
> 
> Created storage name 'admin' manually after login to http://localhost:9000/minio/ in browser.
> 
> Then I was able to upload file to admin storage through postman client
> 
> One file was uploaded through browser using storage user.
> 
> But was able to access the file through different user.
> 
> Please guide.

1) Check uploaded file ( i used my own file in postman parameters )
2) After install you have not any storages in Min.IO. You need add one via Min.OI console OR via request under default admin user.

If tests finished OK, storage works - i create and delete storage under admin and upload/delete files

Documentation in progress ... i will include this data in it

**Comment by leaderit** [comment]
> An update:
> 
> But was able to access the file through different user.
> 
> Please guide.

you may set up access rights to any request in the Hasura console : Actions->SELECT REQUEST->permissions.

default configuration: you can request file upload URL from any users except anonymous.

1. Do request storage_newfile
2. Use returned URL for upload file via PUT request in binary mode. set headers Content-Type, Content-Length, others youneed

**Comment by leaderit** [comment]
>  "status": 500,
>                         "body": {
>                             "error": "Internal Server Error",
>                             "code": "NoSuchBucket",
>                             "message": "The specified bucket does not exist",
>                             "statusCode": 500
>                         },

 "status": 500,
                        "body": {
                            "error": "Internal Server Error",
                            "code": **"NoSuchBucket",**
                            "message": "The specified bucket does not exist",
                            "statusCode": 500
                        },

create the bucket ( storage) via storage_new request (see example in postman - do it under admin)
