### ISSUE TITLE
Disable x-hasura-admin-secret  header in Nginx

### ISSUE THREAD

**Issue by templatedop** [leaderit/graphql-postgres-template#4]
Hi,

Can you please help me in disabling x-hasura-admin-secret in Nginx.

This will help me to make sure that no one can query even from postman client with x-hasura-admin-secret from outside network.

This will be great help. 

Thank you.

**Comment by leaderit** [comment]
Done.

pull updates

also for production you MUST remove if ports exposion (comment ports sections in docker-compose.yaml)

for hasura and other docker services - access via NGINX PROXY ONLY

**Comment by templatedop** [comment]
Thank you.

It worked like charm!

Within local LAN I am accessing through admin secret.

But for outsiders who try access it is not accessible.

Yes will not enable any ports relating to docker services in firewall.

THANK YOU.

Some more configs are required for Nginx.

Will come back brother. THANK YOU.

**Comment by leaderit** [comment]
> Thank you.
> 
> It worked like charm!
> 
> Within local LAN I am accessing through admin secret.
> 
> But for outsiders who try access it is not accessible.
> 
> Yes will not enable any ports relating to docker services in firewall.
> 
> THANK YOU.
> 
> Some more configs are required for Nginx.
> 
> Will come back brother. THANK YOU.

for access to the template from outside use nginx-proxy-manager.

set up additional access restrictions with LONGLONG passwords for access to consoles
and setup https protocol.

it works fine, i tested it long time
