### ISSUE TITLE
Remove Nginx server header

### ISSUE THREAD

**Issue by templatedop** [leaderit/graphql-postgres-template#5]
Hi Brother!

I am trying to remove response header `Server: nginx/1.19.6` 

Can you please guide.

I tried to add server_tokens '';
more_clear_headers Server;

in deafult.conf, the server becomes non responsive.

**Comment by leaderit** [comment]
> Hi Brother!
> 
> I am trying to remove response header `Server: nginx/1.19.6`
> 
> Can you please guide.
> 
> I tried to add server_tokens '';
> more_clear_headers Server;
> 
> in deafult.conf, the server becomes non responsive.

add into server section:

server_tokens off;
more_set_headers "Server: My Very Own Server";

and you get you own Server header as you wish

**Comment by templatedop** [comment]
I tried like this. It didn't work.

Tried in postman. Following error is thrown.

Error: connect ECONNREFUSED (followed by my server IP)

**Comment by templatedop** [comment]
Nginx logs:
/docker-entrypoint.sh: Configuration complete; ready for start up
2021/03/06 04:09:01 [emerg] 1#1: unknown directive "more_set_headers" in /etc/nginx/conf.d/default.conf:12
nginx: [emerg] unknown directive "more_set_headers" in /etc/nginx/conf.d/default.conf:12

**Comment by templatedop** [comment]
May be something to be added in dockerfile?

**server_tokens off;**  works

But **more_set_headers 'Server: My Very Own Server';** is not working.

**Comment by leaderit** [comment]
> May be something to be added in dockerfile?
> 
> **server_tokens off;** works
> 
> But **more_set_headers 'Server: My Very Own Server';** is not working.

i gues, use double quotas
